# ov50 Linux/OSX build - courtesy to https://github.com/seandepagnier
language: cpp
matrix:
  include:
    - env:
        - OCPN_TARGET=xenial
      dist: xenial
      compiler: gcc
      script:
        - sh ./ci/travis-build-debian.sh

    - env:
        - OCPN_TARGET=trusty
      dist: trusty
      compiler: gcc
      script:
        - sh ./ci/travis-build-debian.sh

    - env:
        - OCPN_TARGET=osx
      os: osx
      compiler: clang
      script:
        - bash ./ci/travis-build-osx.sh
        
script:
  - if [[ "${COVERITY_SCAN_BRANCH}" == 1 ]];
    then
      echo "Don't build on coverty_scan branch.";
      exit 0;
    fi
  - ls -l;

notifications:
  email: false
git:
  depth: 10
before_install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
deploy:
- provider: releases
  api_key:
    secure: "POphzrmCdwTYoQLpG0/ZAA7a/j56FQEFkihzLlOMNNK0fOosL11fjZeGJviZ4UI0sS3OPvRlIFiPIx6nDpHaNBZEfyOR6cmSv+KCh4nkLu5bhJ84VUuE6YqMA+EdsJWJutbpS7Z/l6/LEtHcnOHhyXVIqRwpTB3Mh5ETuW6EYhjyEWz6mCgSYak6FqbY/X6OuYADaeh+DsAVwmsLCAEwu0vWySFPOfl2qG+NsQBPJtkjhhpfSlGiNlPY+inwwQc9KlBfG0MLYu+yMos/EuZ2CJjDXJyQYAm2lBMcyScJneQnFDhz8OcFTxSXbS0XglPPC12WgRquZD9AVbOtQCsuo38bFZUUV+bcb6QkLCaphtNTAkM5r4Oae4gqk9Sl3cLzYmIW+j8MQ+IDmgvgVEfk1dNqoHMzgtJTImkynRbfWGf0BOy1tNve4EI5VAX8NRWX8O9P3XcS8QrWRL/g8o2MMwhS8fkeBw1UamrREieAktheZ+6h/JsTtXowPNz76Uoicrfl+DnYgYC0XjgfDBjjtVNwvFFeI9ch76T3N23n1gxA9j70lYPLjc43I4is2xJruSlduyFwkoN5qofuWwBG+mteH/e7NdkbODN5ESFu1iyC1eafnGlHAeFuDIadlRxOXr0e9p5Cvn1oD68GcG9TMAXPAOUXaYgtPl5Wk+BVX4I="
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/build/*.{deb,pkg}"

  skip_cleanup: true
  on:
    repo: rgleason/squiddio_pi
    tags: true
    all_branches: true
