language: cpp

  
matrix:
  include:
  - env:
    - OCPN_TARGET=stretch-armhf
    - OCPN_BRANCH=master
    - OCPN_STABLE_REPO=mauro-calvi/squiddio-stable
    - OCPN_UNSTABLE_REPO=mauro-calvi/squiddio-pi
#    - OCPN_PKG_REPO=mauro-calvi/squiddio-manual
    - DOCKER_IMAGE=raspbian/stretch
#/~mauro-calvi/repos/squiddio-stable
#/~mauro-calvi/repos/squiddio-pi
#/~mauro-calvi/repos/squiddio-manual
    services:
    - docker
    script:
    - "./ci/travis-build-raspbian-armhf.sh"
  - env:
    - OCPN_TARGET=buster-armhf
    - OCPN_BRANCH=master
    - OCPN_STABLE_REPO=mauro-calvi/squiddio-stable
    - OCPN_UNSTABLE_REPO=mauro-calvi/squiddio-pi
#    - OCPN_PKG_REPO=mauro-calvi/squiddio-manual
    - DOCKER_IMAGE=raspbian/stretch
#/~mauro-calvi/repos/squiddio-stable
#/~mauro-calvi/repos/squiddio-pi
#/~mauro-calvi/repos/squiddio-manual
    - DOCKER_IMAGE=opencpn/raspbian-buster:plugin_build_tooling
    services:
    - docker
    script:
    - "./ci/travis-build-raspbian-armhf.sh"


branches:
  only:
    - master

