# ov50 Linux/OSX build - courtesy to https://github.com/seandepagnier
language: cpp
matrix:
  include:
    - env:
        - OCPN_TARGET=xenial
      dist: xenial
      compiler: gcc
      script:
        - sh ./ci/travis-build-debian.sh

    - env:
        - OCPN_TARGET=trusty
      dist: trusty
      compiler: gcc
      script:
        - sh ./ci/travis-build-debian.sh

    - env:
        - OCPN_TARGET=osx
      os: osx
      compiler: clang
      script:
        - bash ./ci/travis-build-osx.sh
        
script:
  - if [[ "${COVERITY_SCAN_BRANCH}" == 1 ]];
    then
      echo "Don't build on coverty_scan branch.";
      exit 0;
    fi
  - ls -l;

notifications:
  email: false
git:
  depth: 10
before_install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
deploy:
- provider: releases
  api_key: "squiddio-git-ptoken-into-app-trav"
    secure: "PjD13cClbZncs59iluPvJqaecu2BYPnEbSXT3cDrKlz8dbz4541gyWNALzQJvvjgQ682WlbwzzlOe+RYA+DCOm8sm8z2sV4Gt+ognovEqGSNx+DvWZ9/tWG27OmJZylKywp/gJGmI+z5W8trm/0GQuUk4Um0fVhrhARSKfEM562nAe7PyInS24Lwa5en4YeomhsRCzWlvavqbxgUq76CzOSlKBv5TWOiOltDHRxQgFgyLg6WxN3wRc9grv3SyZA0JaRtHhDL/gIc5P6l5Dmu+qAKVL6Be4ldKwyTXmxP2+Xc0C9TTAgi2UmQHbRXuHZ6VYQEBiLvMR5i3VV6/t/nT8XtZwCBX7sKls1CqqkDdm+npBjIJ1PRiuxJ3hpfS0klKTXJHjyrqXjNSBoaKmoQDLS6pxwQzibfroq8rg26ZU3FeclIogPAt6VQj8eQaGFxFAHLzBEitpqxUcFBlcKkhRVIgA5MWejMqm6GJRvTCMllEmiKRGUgSbjzwnrQVeC1mWtGIS/raVcaM7012bQG8U8pBytcT+Ef6gxMQK8k0l8bI3JJmZttFysFeM5t8qhNp1E456SirCZmCteJVpYLeNc90moQ7KzUlMhTunMdOxzHJjUlcySqfvnyHdAoBqW0XSkqPTz7FWSIzmUtsogyQM1RhD5JlYIrgwPyPZbNc9c="
# "ITY5bfgEHsABqkzibS60y9W3so4eht4ociqAE7H0gnFA/3h3aVXyaZZvUhSQF8XwaWgTDfgxJOvPvOsY+mYNN5GOOSFd0YwRxKA8ys8TPqB2T2MkQ5lt9+5pJ52VkJ8cR1Ro688k5NEZmavke29QHVuzOfaNWPqAx1Xfkp/Vnbw1ApB5mQiNwQKtfkI8dZDtP/IFYHSF8+2gRuCe9i/Ed+yUfpojRSb15X/qs2+l57VOKrR//J21iqZ+hYRQKzfqs6QOyb2B822ABJuI6kESzVWg2vtO1mI4XD3dv6BIaWnzHiwIk8nbI0TAuYTR/Yze4jACqSa6ud9I1KLT3trbw9ZFRODiFniSGIjqEpZG5S1FMK7TLK0+a8Lk5GHqDJn5T+mVxljSPO3rcMtWqa51uar4FFyUVgPL1bBd5FgsRkRNulV5O6I89rDmtgoc0UzUBy7WrO/JrT2AEoe4WiYM7BYxjRHTcW1+dHGr/y1CU3sIvcR/0BdZuTDfET5NV5zl6AabJUcyi5M7p2wmW0In2OAJzCWuRGthTmAx9xeUiXAbNzSCpkozKSZDRJnTLpvyBm4RzsqiWZKoKgFRP2AFpkh6E23e9REdKih5nTkD19aEKj7uXFViEojAQ13RqcchksQyzZ33u0mgJ2i2aX0x8eFG8qbYXMgB6t7pMrmq9tY="
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/build/*.{deb,pkg}"
  skip_cleanup: true
  on:
    repo: rgleason/squiddio_pi
    tags: true
    all_branches: true
