# ov50 Linux/OSX build - courtesy to https://github.com/seandepagnier
language: cpp
matrix:
  include:
    - env:
        - OCPN_TARGET=xenial
      dist: xenial
      compiler: gcc
      script:
        - sh ./ci/travis-build-debian.sh

    - env:
        - OCPN_TARGET=trusty
      dist: trusty
      compiler: gcc
      script:
        - sh ./ci/travis-build-debian.sh

    - env:
        - OCPN_TARGET=osx
      os: osx
      compiler: clang
      script:
        - bash ./ci/travis-build-osx.sh
        
script:
  - if [[ "${COVERITY_SCAN_BRANCH}" == 1 ]];
    then
      echo "Don't build on coverty_scan branch.";
      exit 0;
    fi
  - ls -l;

notifications:
  email: false
git:
  depth: 10
before_install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
deploy:
- provider: releases
  api_key: "squiddio-git-ptoken-into-app-trav"
    secure: "B7nXHKOPXyj/A+HCyulnM+mRUmrloSKO+o29jXlzCNrXx8BuKQU3UIGPVYSV41XAc03Kpzc/SMCmHTSoi9mIGQQ6OY/f2xQHGO0z+wi5prfCelswPzQvjmKB6gqfYgp1lCHiwVnsrgCaL1HmkG/F4CnT+Y1PZM7D1J9xshCsovaTTQvJv1cUPpvwyPoYQVDF/bAxvokbAQASRYbZWhn2AfcUoT5XIiwBL+BXUuVoTfVUSXzj0FS+f/ke0Mg+SSj3BoLLQYUz8sate92Ns3Ols56IFTDdWsotR69bzsgfUsEKc6yn0RRJLVkfh5re6g52rr+7sl7DAtIyoEPpftmzpt4tg0hpYZZ/yJ9p1jBCrfYHPNp6FYplRPaIzu77tdidcP4eRBhIYqJBpG3BCJDPEdnjW5FBHeWxzFMJllnawG/jxIx0/gapKGTLlpx5LEYFf7IymJ9brud3Qm7aW20rf9V9umq8h9eHIKlbROT2vmSQvOFBefy6RBD9nz9McsI1IKdZ69adNJpa0Up179I5tHstnzWlJgC7L4ywAsRVV+IpZ1JePkkOP+LnTRFSIthVpgRs4XazFiQN5Iem3eitqEP0SPigXFfRfqUuGBL5HA6FMat+kgI04aqUMHPotZgdvQyXYza4WtavD5vQv3mylS9RBGvDIpYmPXPB2FJ9dok="
# "ITY5bfgEHsABqkzibS60y9W3so4eht4ociqAE7H0gnFA/3h3aVXyaZZvUhSQF8XwaWgTDfgxJOvPvOsY+mYNN5GOOSFd0YwRxKA8ys8TPqB2T2MkQ5lt9+5pJ52VkJ8cR1Ro688k5NEZmavke29QHVuzOfaNWPqAx1Xfkp/Vnbw1ApB5mQiNwQKtfkI8dZDtP/IFYHSF8+2gRuCe9i/Ed+yUfpojRSb15X/qs2+l57VOKrR//J21iqZ+hYRQKzfqs6QOyb2B822ABJuI6kESzVWg2vtO1mI4XD3dv6BIaWnzHiwIk8nbI0TAuYTR/Yze4jACqSa6ud9I1KLT3trbw9ZFRODiFniSGIjqEpZG5S1FMK7TLK0+a8Lk5GHqDJn5T+mVxljSPO3rcMtWqa51uar4FFyUVgPL1bBd5FgsRkRNulV5O6I89rDmtgoc0UzUBy7WrO/JrT2AEoe4WiYM7BYxjRHTcW1+dHGr/y1CU3sIvcR/0BdZuTDfET5NV5zl6AabJUcyi5M7p2wmW0In2OAJzCWuRGthTmAx9xeUiXAbNzSCpkozKSZDRJnTLpvyBm4RzsqiWZKoKgFRP2AFpkh6E23e9REdKih5nTkD19aEKj7uXFViEojAQ13RqcchksQyzZ33u0mgJ2i2aX0x8eFG8qbYXMgB6t7pMrmq9tY="
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/build/*.{deb,pkg}"
  skip_cleanup: true
  on:
    repo: rgleason/squiddio_pi
    tags: true
    all_branches: true
